"""add app_settings table

Revision ID: 283d167ad283
Revises: ba6c10699eb0
Create Date: 2026-08-29 16:14:17.203260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = '283d167ad283'
down_revision: Union[str, Sequence[str], None] = 'ba6c10699eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'app_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('registration_enabled', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    
    op.bulk_insert(
    table('app_settings', column('id', sa.Integer), column('registration_enabled', sa.Boolean)),
    [{'id': 1, 'registration_enabled': True}],
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
